pytest: Fix tests execution in development virtual environment
Since migration to PEP 517, executing "make test" or "pytest" in the root
directory of the scanner package triggers the following error:

ModuleNotFoundError: No module named 'swh.data'

Explicitly setting the testpaths option in pytest.ini and TEST_DIRS
variable in Makefile.local to swh/scanner/tests fix the issue.